spring.application.name=BffAgendadorTarefas
server.port=8083

usuario.url=localhost:8080/usuario
agendador-tarefas.url=localhost:8081/tarefas
notificacao.url=localhost:8082/email

cron.horario=0 0/5 * * * ?

usuario.email=${CRON_USER_EMAIL}
usuario.senha=${CRON_USER_SENHA}
